// with command line 'install', we need to append to the the start command a '&& leasot-to-readme run' (series)

// requires and vars
var fs = require('fs');
var findInFiles = require('find-in-files');
const sDefaultTemplate = '# TODOs and FIXMEs generated by leasot-to-readme\n';
const sDefaultFileName = 'README.md';
var OUTPUT_FILE = 'README.md';
var COMMAND = 'start:';
var iLineCount = 0;

var lineReader = require('readline').createInterface({
  input: require('fs').createReadStream('package.json')
});

lineReader.on('line', function (line) {
  if (!line.contains(COMMAND)) {
    iLineCount++;
  }
});

// append the command to the line number where 'start' command occurs
var data = fs.readFileSync(OUTPUT_FILE).toString().split("\n");
data.splice(iLineCount, 0, "&& leasot-to-readme run");
var text = data.join("\n");

// write back the output file
fs.writeFile(OUTPUT_FILE, text, function (err) {
  if (err) return console.log(err);
});
