// with command line 'install', we need to append to the the start command a '&& leasot-to-readme run' (series)

// requires and vars
var fs = require('fs');
var findInFiles = require('find-in-files');
const sDefaultTemplate = '# TODOs and FIXMEs generated by leasot-to-readme\n';
const PACKAGE_JSON = 'package.json';
var OUTPUT_FILE = 'README.md';
var COMMAND = '"start":';
var iLineCount = 0;

var lineReader = require('readline').createInterface({
  input: require('fs').createReadStream(PACKAGE_JSON)
});

lineReader.on('line', function (line) {
  if (!line.includes(COMMAND)) {
    iLineCount++;
  }
});

// append the command to the line number where '"start":' command occurs in package.json
var data = fs.readFileSync(PACKAGE_JSON).toString().split("\n");
data.splice(iLineCount, 0, "&& leasot-to-readme run");
var packageJSON = data.join("\n");

// write back to package.json
fs.writeFile(OUTPUT_FILE, packageJSON, function (err) {
  if (err) return console.log(err);
});
