// the main run command - run leasot and append the returned text to the readme

// requires and vars
var fs = require('fs');
var exec = require('child_process').exec;
const TITLE_MD = '# TODOs and FIXMEs generated by leasot-to-readme:\n';
var OUTPUT_FILE = 'README.md';
var sCustomTemplate = null;
var sTemplate;
var sContents;

console.log('in run!!!');

// get leasot output:
exec('leasot * --ignore node_modules/* *.md', function(code, sLeasotOutput, stderr) {
  console.log(sLeasotOutput);
  // template logic
  if (sCustomTemplate) {
    sTemplate = sCustomTemplate;
  } else {
    sTemplate = TITLE_MD
  }
  sContents = sTemplate + sLeasotOutput;

  // if we already wrote there, delete and replace

  // else, append sContents to README.md
  fs.appendFileSync(OUTPUT_FILE, sContents, function (err) {
    if (err) throw err;
    console.log('Leasot output written to ' + OUTPUT_FILE + ".");
  });
});
