// the main run command - run leasot and append the returned text to the readme

// requires and vars
var fs = require('fs');
var findInFiles = require('find-in-files');
const TITLE_MD = '# TODOs and FIXMEs generated by leasot-to-readme\n';
var OUTPUT_FILE = 'README.md';
var sCustomTemplate = null;
var sTemplate;
var sContents;

// get leasot output:
var sLeasotOutput = function(callback){
    execute("leasot src/*", function(sResults){
        callback(sResults);
    });
};

// template logic
if (sCustomTemplate) {
  sTemplate = sCustomTemplate;
} else {
  sTemplate = TITLE_MD
}
sContents = sTemplate + sLeasotOutput;

// if we already wrote there, replace

// else, append to README.md
fs.appendFile(OUTPUT_FILE, sTemplate, function (err) {
  if (err) throw err;
  console.log('Saved!');
});
