// the main run command - run leasot and append the returned text to the readme

// requires and vars
var fs = require('fs');
var findInFiles = require('find-in-files');
const sDefaultTemplate = '# TODOs and FIXMEs generated by leasot-to-readme\n';
const sDefaultFileName = 'README.md';
var sFileName = 'README.md';

// get leasot content:
sLeasotContent = function(callback){
    execute("leasot src/*", function(sResults){
        callback(sResults);
    });
};

// template logic
if (sCustomTemplate) {
  sTemplate = sCustomTemplate;
} else {
  sTemplate = sDefaultTemplate
}
sContents = sTemplate + sLeasotContent;

// if we already wrote there, replace

// else, append to README.md
fs.appendFile(sFileName, sTemplate, function (err) {
  if (err) throw err;
  console.log('Saved!');
});
